---
kind: "operation"
client: "atomist-bot"
generator:
  name: "NewSpringBootRestService"
  group: "atomist-rugs"
  artifact: "spring-boot-rest-service"
  version: "0.9.0"
  origin:
    repo: "https://github.com/atomist-rugs/spring-boot-rest-service.git"
    branch: "bbeb8db6235597154ebdd20a7d9c4bdb924b5b33"
    sha: "bbeb8db"
  parameters:
    - "project_name": "survey-options"
    - "artifactId": "survey-options"
    - "groupId": "com.jessitron"
    - "version": "0.1.0-SNAPSHOT"
    - "description": ""Supply list of options for a survey""
    - "rootPackage": "com.jessitron"
    - "serviceClassName": "SurveyOptions"

---
kind: "operation"
client: "rug-cli 0.29.0"
editor:
  name: "ConvertExistingProjectToGenerator"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.24.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "cff978c59d1635572a8de584f1a1daad5e8d7a68"
    sha: "cff978c"
  parameters:
    - "archiveName": "sol-spring-rest-service"
    - "groupId": "satellite-of-love"
    - "version": "1.0.0"
    - "generatorName": "NewRestService"
    - "description": "A company-standard REST service"

---
kind: "operation"
client: "atomist-bot"
editor:
  name: "RestrictCORS"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.9"
  origin:
    repo: "git@github.com:satellite-of-love/workflow-rugs"
    branch: "master"
    sha: "5d3e90e"

