Feature: Tests from NewRestService.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.


  Scenario: NewRestService should create a new project based on this archive
    Given an empty project
    When NewRestService for NewRestService should create a new project based on this archive
    Then parameters were valid
    Then fileExists README md for NewRestService should create a new project based on this archive
